#!/bin/bash

# Load resources
xrdb -merge .Xresources

# Set up an icon tray
trayer --edge top --align right --SetDockType true --SetPartialStrut true \
     --expand true --width 15 --transparent true --tint 0x000000 --height 22 &

# Set the background color
xsetroot -solid black

# Fire up apps
xscreensaver -no-splash &
if [ -x /usr/bin/nm-applet ] ; then
    nm-applet --sm-disable &
fi
gnome-power-manager &
autokey &
ibus-daemon &
dropbox start
exec xmonad

